#' Synthetic repeated groundwater-monitoring events
#'
#' Two small UTC monitoring events on a planar-to-gently-curved synthetic head
#' field. Membership changes between events and event B includes a known head
#' decline. Values are generated, not observations from a real aquifer.
#'
#' @format A data frame with 36 rows and fields for well ID, projected
#'   coordinates (metres, EPSG:26916), UTC time, event, head (metres), quality,
#'   unit, vertical datum, and explicit water-bearing unit.
#' @source Generated by `data-raw/generate-expansion-data.R` with seed 20260717.
"synthetic_events"

#' Synthetic nested monitoring wells
#'
#' Eight two-interval nests containing known upward, downward, and near-zero
#' vertical-gradient cases. Screen and representative elevations are absolute
#' metres in the named synthetic vertical datum.
#'
#' @format A data frame with 16 interval records.
#' @source Generated by `data-raw/generate-expansion-data.R`.
"synthetic_nested_wells"

#' Two synthetic interpolation compartments
#'
#' Adjacent disconnected-analysis rectangles supplied as explicit WKT. They are
#' user-defined compartments, not inferred aquifers or flow boundaries.
#'
#' @format A two-row data frame with region IDs, bounds, WKT, and CRS.
#' @source Generated by `data-raw/generate-expansion-data.R`.
"synthetic_regions"

#' Synthetic surface shapes and hydrogeologic covariates
#'
#' A small projected grid containing land-surface elevation, distance from a
#' valley axis, and known planar, bowl, saddle, and elongated-valley head
#' surfaces. These are mathematical fixtures, not real aquifers.
#'
#' @format A 224-row grid in EPSG:26916; elevations and heads are metres and
#'   distances are metres.
#' @source Generated by `data-raw/generate-expansion-data.R`.
"synthetic_covariates"

#' Synthetic candidate monitoring sites
#'
#' Twelve explicit candidate coordinates with exclusions, costs, and arbitrary
#' user scores for constraint and ranking examples. The coordinates are not
#' proposed drill sites.
#'
#' @format A 12-row data frame in EPSG:26916.
#' @source Generated by `data-raw/generate-expansion-data.R`.
"synthetic_candidate_sites"

#' Synthetic cross-section transect
#'
#' One projected polyline for profile and cross-section examples.
#'
#' @format A one-row data frame with WKT and EPSG:26916.
#' @source Generated by `data-raw/generate-expansion-data.R`.
"synthetic_transect"

#' Synthetic anisotropic head points
#'
#' A fixed-seed elongated periodic field with a generating major-continuity
#' direction of 35 degrees clockwise from north. Sampling noise and finite
#' extent mean exploratory estimates need not equal 35 degrees exactly.
#'
#' @format A 45-row projected point table with head in arbitrary consistent
#'   elevation units.
#' @source Generated by `data-raw/generate-expansion-data.R` with seed 20260717.
"synthetic_anisotropic_points"

#' Synthetic independent validation points
#'
#' Fourteen fixed-seed points sampled independently from a known planar head
#' field with small Gaussian measurement perturbations.
#'
#' @format A 14-row projected point table in EPSG:26916 with head in metres.
#' @source Generated by `data-raw/generate-expansion-data.R` with seed 20260717.
"synthetic_validation_points"
